export const styles = {
  container: {
    maxWidth: "600px",
    margin: "0 auto",
    fontFamily: "system-ui, -apple-system, sans-serif",
    backgroundColor: "#ffffff",
    minHeight: "100vh",
    padding: "2rem 1.5rem",
  },
  header: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "2.5rem",
    borderBottom: "2px solid #e0e0e0",
    paddingBottom: "2rem",
    backgroundColor: "#6b46c1",
    borderRadius: "12px",
    paddingTop: "2rem",
  },
  title: {
    fontSize: "30px",
    fontWeight: "700",
    margin: 0,
    letterSpacing: "-0.5px",
    textAlign: "center",
    color: "#ffffff",
  },
  subtitle: {
    fontSize: "15px",
    fontWeight: "500",
    color: "#e9e1fa",
    margin: 0,
    marginTop: "0.5rem",
    textAlign: "center",
  },
  tabs: {
    display: "flex",
    gap: "0.5rem",
    marginBottom: "2.5rem",
    borderBottom: "2px solid #e0e0e0",
    overflowX: "auto",
    paddingBottom: "1rem",
  },
  tab: {
    padding: "0.75rem",
    border: "2px solid #e0e0e0",
    backgroundColor: "#fff",
    cursor: "pointer",
    fontSize: "26px",
    color: "#666",
    borderRadius: "8px",
    minWidth: "52px",
    minHeight: "52px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    lineHeight: 1,
  },
  tabActive: {
    backgroundColor: "#333",
    border: "2px solid #333",
  },
  content: {
    marginBottom: "2rem",
  },
  card: {
    backgroundColor: "#f9f9f9",
    border: "2px solid #e0e0e0",
    borderRadius: "12px",
    padding: "2rem",
    marginBottom: "2rem",
  },
  cardTitle: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#333",
    marginBottom: "1.5rem",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    letterSpacing: "-0.3px",
  },
  cardLabel: {
    fontSize: "18px",
    color: "#666",
    marginTop: "1.25rem",
    marginBottom: "0.6rem",
    fontWeight: "600",
  },
  formGroup: {
    marginBottom: "2rem",
  },
  label: {
    display: "block",
    fontSize: "18px",
    fontWeight: "700",
    marginBottom: "0.8rem",
    color: "#333",
    letterSpacing: "-0.2px",
  },
  input: {
    width: "100%",
    padding: "1.25rem",
    fontSize: "20px",
    border: "2px solid #d0d0d0",
    borderRadius: "8px",
    boxSizing: "border-box",
    minHeight: "56px",
  },
  select: {
    width: "100%",
    padding: "1.25rem",
    fontSize: "20px",
    border: "2px solid #d0d0d0",
    borderRadius: "8px",
    boxSizing: "border-box",
    minHeight: "56px",
  },
  textarea: {
    width: "100%",
    padding: "1.25rem",
    fontSize: "20px",
    border: "2px solid #d0d0d0",
    borderRadius: "8px",
    minHeight: "120px",
    boxSizing: "border-box",
    fontFamily: "inherit",
    resize: "vertical",
  },
  button: {
    padding: "1.25rem 2rem",
    backgroundColor: "#333",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "20px",
    fontWeight: "700",
    minHeight: "56px",
    width: "100%",
    letterSpacing: "-0.3px",
  },
  deleteButton: {
    padding: "0.6rem 0.9rem",
    backgroundColor: "#e74c3c",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "600",
  },
  editButton: {
    padding: "0.6rem 0.9rem",
    backgroundColor: "#f0f0f0",
    color: "#333",
    border: "2px solid #d0d0d0",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "600",
  },
  saveButton: {
    padding: "0.6rem 0.9rem",
    backgroundColor: "#27ae60",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "600",
  },
  cancelButton: {
    padding: "0.6rem 0.9rem",
    backgroundColor: "#f0f0f0",
    color: "#666",
    border: "2px solid #d0d0d0",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "600",
  },
  editInput: {
    width: "100%",
    padding: "0.6rem",
    fontSize: "16px",
    border: "2px solid #d0d0d0",
    borderRadius: "6px",
    boxSizing: "border-box",
    marginBottom: "0.5rem",
  },
  entry: {
    backgroundColor: "#fff",
    border: "2px solid #e0e0e0",
    borderRadius: "10px",
    padding: "1.5rem",
    marginBottom: "1.25rem",
    fontSize: "18px",
    color: "#333",
    lineHeight: "1.8",
    fontWeight: "500",
  },
  entryMeta: {
    fontSize: "16px",
    color: "#999",
    marginTop: "0.75rem",
    fontWeight: "400",
  },
  emptyState: {
    textAlign: "center",
    color: "#999",
    fontSize: "18px",
    padding: "2.5rem 1.5rem",
  },
  twoColumnForm: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1.5rem",
  },
};
